<?php

namespace App\Controller;

use App\Controller\Component\InvoicesDataTableComponent;

/**
 * Invoice Controller
 *
 * @property \App\Model\Table\InvoiceTable $Invoice
 * @property InvoicesDataTableComponent $InvoicesDataTable
 *
 * @method \App\Model\Entity\Invoice[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class InvoiceController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('InvoicesDataTable');
    }


    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {

    }

    public function list()
    {
        $request = $this->getRequest();

        $invoice = $this->Invoice->query()
            ->select(['id', 'code', 'total', 'company', 'address', 'email']);

        $this->InvoicesDataTable->filter($invoice, $request);
        $this->InvoicesDataTable->search($invoice, $request);
        $this->InvoicesDataTable->paginate($invoice, $request);

        $this->set([
            'data' => $invoice,
            'recordsTotal' => $this->Invoice->query()->count(),
            'recordsFiltered' => $invoice->count(),
            '_serialize' => ['data', 'recordsTotal', 'recordsFiltered']
        ]);
    }

    /**
     * View method
     *
     * @param string|null $id Invoice id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view()
    {
        $invoice = $this->Invoice->get($this->request->getParam('id'));
        $this->set('invoice', $invoice);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $invoice = $this->Invoice->newEntity();
        if ($this->request->is('post')) {
            $invoice = $this->Invoice->patchEntity($invoice, $this->request->getData());
            if ($this->Invoice->save($invoice)) {
                $this->Flash->success(__('The invoice has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The invoice could not be saved. Please, try again.'));
        }
        $this->set(compact('invoice'));
    }

    /**
     * Edit method
     *
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit()
    {
        $invoice = $this->Invoice->get($this->request->getParam('id'));
        if ($this->request->is(['patch', 'post', 'put'])) {
            $invoice = $this->Invoice->patchEntity($invoice, $this->request->getData());
            if ($this->Invoice->save($invoice)) {
                $this->Flash->success(__('The invoice has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The invoice could not be saved. Please, try again.'));
        }
        $this->set(compact('invoice'));
    }

    /**
     * Delete method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete()
    {
        $invoice = $this->Invoice->get($this->request->getParam('id'));
        if ($this->Invoice->delete($invoice)) {
            $this->Flash->success(__('The invoice has been deleted.'));
        } else {
            $this->Flash->error(__('The invoice could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}
